config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:new, :create, :show, :index] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  root to: "lists#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params['list_id'])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    Rails.logger.debug "List found: #{@list.inspect}"

    @bookmark = @list.bookmarks.find(params[:id])
    Rails.logger.debug "Bookmark found: #{@bookmark.inspect}"

    if @bookmark.destroy
      redirect_to list_path(@list), notice: 'Bookmark was successfully deleted.'
    else
      Rails.logger.debug "Failed to delete Bookmark: #{@bookmark.errors.full_messages}"
      redirect_to list_path(@list), alert: 'Failed to delete Bookmark.'
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      Rails.logger.debug "Params: #{params.inspect}"
      movie_ids = params[:list][:movie_ids].reject(&:blank?) rescue []
      movie_ids.each do |movie_id|
        Bookmark.create(list: @list, movie_id: movie_id)
      end

      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, movie_id: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a Bookmark to <%= @list.name %></h1>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment, label: 'Comment' %>

  <%= f.association :movie, collection: Movie.all, label_method: :title, value_method: :id, prompt: 'Select a movie' %>

  <%= f.submit "Add Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div>
  <h1>Lists</h1>
  <%= link_to "New list", new_list_path%>
</div>

<div class="container">
  <ul>
    <% @lists.each do |list|  %>
    <li>
    <%= link_to list.name, list_path(list) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<h1>Add a new list</h1>

<%= form_with model: @list, local: true do |element| %>
  <%= element.label :name %>
  <%= element.text_field :name %>
  <%= element.submit%>
<% end %>

<%= link_to "back to lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
  <%= link_to "back to lists", lists_path %>
  <%= link_to "add a bookmark", new_list_bookmark_path(@list) %>
  <% @list.movies.each do |movie|  %>
    <p><%= movie.title %></p>
    <p><%= movie.overview %></p>
    <p><%= movie.title %></p>
    <p><%= image_tag "#{movie.poster_url}" %></p>
    <p><%= link_to 'Delete', list_bookmark_path(@list, movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} %></p>
  <% end %>